site:
  appname		: ushare
  port	        : 4000
  runmode		: dev

mysql:
  host 		: 127.0.0.1
  username 	: root
  password 	: tustar
  database 	: ushare
  port		: 3306

api:
  apikey		: 1001
  apisecrect	: tustar

token:
  key  : tustar

build:
  debug : true
